apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: keycloak-admin
  namespace: keycloak
spec:
  encryptedData:
    password: AgB4AcFJ/8ucsIyaktxZhCBRPftC/lBtarozn5t8OdwGuuPNHXcslg9OPGzw1J3UaM6ahyTkKbTuCv2CgOtYwNAQHV+O6VnLizj40GFFtyr8jMiyYtqcQGJfGubOXNh3wGY1RnLkUJCV5I7996Y2h2Y/0WXDISNBY2mZ2GoA6pqgOLmnfglLI5qFS2iufrOiZFGdz/1UWP2bDMRbmN4vUZtPZu/imiiI6odQjsCuSU/vZVc5TMq4UXn4C5S2NJrjRWE36Z+UASOiPSf7PG6MsALDPrlyOGlWERQBLnbYaXrqawNlZQcyMzEBUnL5TCrbf1IAdbvUcLoiLAVUvxuewSUn/R78KsRLWkU1FJwv+bspspopKOiVgoZPBk41Y2J46Zt8ZTidfIiEmC1ddfbSTufYdh/h5pbQpbLgoFrubmVe1TSzPWMVN6ns31HyJgAPW6T9OC9dbEsFAVYFMiwdl+xtgFFwPJAmXsq7dJaYu12fWUeEH66y7KGpOnmVf8iBE+zQ2hb8SZomjlChDhjGdHZsXtonvCDGL8aJcBFanVuSq8Adv9bQ6q3LBox4IBbFpdUme/620h1nCTL+tsEZo1R2etxG0kTniKutz30rjAO4Nmh1n/T6RRvwxo6I0fkQqXiMxItACgjDSmrCJJZ8Qx6ByoLt9fA1wakC24BoETuspMRcwHFxHaUFcRElREn3SIdArf0sI4nbphVzcQ==
    username: AgCSktM20oVRol73nioFVQCi0bdAJToEYGEI9lJ9gjRFbehBgV/mmceKB5kzUBe5SADiFiVBNvqwCBUqa8KxFyzhwkCRAraVF1fRYFYBDJK0EeA0E6G5lM4azubjICFg7xvzwLCk1PP+gKu1NtcascTg1yYFdDdDX/vcXMMjQ0pnDW+O5TSrne895iMgqeXb7Ff9NhUww0seX5Dd/x06ZlsWzOjqkAp1yGmnhghshQXcEylARwR5Baei2mHXDkPHQboj6+0+4QIgH2iAhaassW7pjlVZxm20uluOb7Pe/8pibLeVzhynVpabesitnyvFsE5TFQ9W1FyBkox8LULVFhXT/4xcC9MCKcKpXNOnK3s48OxPQkCvEbG4GvGggHhslJIE34qA0/NxyROytg8MTGjeCaBTASzFxr37L5HMNKW7m79h7hsmxJfBTKXsv3v6zk0zGL68df6iBL2nRWuXk2gUot2N2NN1+4i6WLHgeYFtCkvF9seVAx7J6dPZohjqxMR3EVr0bfKnAMWPm30lUHZPSE7KdcaEPkgxyu2siJC5P+2RJlrDxWtpj2zo2xjN57IQVpLeqRfdVHrkTSrdw6G+quTh4fVcPJVqz2jz9yiwxo1wny1NetoOkQ1+mLZq4uqGcugv6LNFO5/XgBvWIX2TEmOG2GuRJ3PlhECRuu5IKFRGKm+hXR8W7oa2Q0+IwrYVnv4JpA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: keycloak-admin
      namespace: keycloak
    type: Opaque

