apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: keycloak-admin
  namespace: keycloak
spec:
  encryptedData:
    password: AgA41Cz1qkBfSituGAFDV1zLZ8JHMWM4SD46430imow5vBG5EcDEuSBqbDJpd3UI38bAjuicioR0+LMHQTrGExALW9puy8gUhI1FQKBpO2d0uv5bwG3vzQ8IDLE76fote7hcQAO/Q2Xt6UQxsC2Zji0rG21N7iYsTshd35Kdvj+ufzeGA6CDdndNjIlBOig9iQeVAe/C6dPo2Q64y4z5kqeHCgoNfyDW/24TJpESGCrs4p+2XSB8OPpOyB6dixhy2vnEDLQSjZbOmKxE58ON9e0Ax9hoFbjN1OS6pIFRwl13H5YROQANmgWELVuH601s25KN+AVKxTHSZWHK8133A6hxIRNsJHEVXE/v/KPfW8q/ZhSwYZbPB+tLEXq0Rba5ir/q7RhaEEvjPiY9LrhoSb3olRs9zUlymyn6d1/WOAhxs1WlGFzA43vvHDISyjlbBuChNp5KAptubUWNy1eSg2xhEAlRRlR4k3+y7kD75uVYmEygKTAeBd3lJBEN5URvwW+idcMFkGnhYIfDIFuLX3he/gBw5nOI6vLDcsC3A7YBiNP0LrrvQ1nxM6kHvmODTuuU+6gEVt+ZEeSGqP9gnTwoFZBd+JEeYzUZrx4VnNJCYQWmn9L56sXnfZYc93sWNRfOUF8ibifXUPiJYEfOgqzYIgzteEQRc9Gdh7JeC4hVUgbt7KG2FgCjcPvLN2dNTTEjbhqBG0Jr374FMuqs9Zo0r0CaI63DW0nb3Pb8wKmQdw==
    username: AgANKStwxe35EaoS6GPecp0q63jV2lyMqZqR7XmcHHYeQvD5KJy0NQNbnckRyG2Z7uoh4AuOOHnpnzcltkQQAR+h1rmiPIOe3XoDRyJHXCJT/45dROe6s+g87jSl9Rnl5QxfYt9MklNBp4OGYcT920DnXlFLTse+Gh8Fmw/B403xFh4sFgKek/4aSkPoPi/VyPYHYD6ZDANu3bjdgCYM2nOrj28NnaxCzbm0SfQw76DIK6whFiQ4POImbMgshfM22YJdmfCpdou1Gs8hjaYYAAX/Fy9Q+0LOPVpH0ZAPjSXpn8oOi0sLrKVeTezporWnioX1hI5BnfkH6cAAIWNx/BBEIFH9ixKa15bvkg57YKeBwLRPhzOT7mtJ7r/Z5Fq5PDPxzzPhWFXQnPzPSyHA0O49747qbU2NnMq9XVMEvNqKSQq5kcLVgzxfI+xTdEiHiL81J11vrcmkeKb5uGE8IxzBCt+iAD7GknBumJQmjRw50cEfFb49SDbOF78/Gvkws9KlLd7qSgyNe/CyFZf4nTt5K5b4OrmOq+sBI1NWhudqvGLD+d2974go1P1VN8exuxIp5nGTByT0xZ0+UrSIe87ncjT7TkOX3W/FYPovHCwjMoOce1wK+6c+cmgoyW6WeTuDBGMyp1ZgD5emXY/xO3mVZ9DPjDbtlt05MZ6arTp9spBY2ml/fsYQfFMqgeEh6dYAgjjp5Q==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: keycloak-admin
      namespace: keycloak
    type: Opaque

